[[neuron_type]]
name = "L5_spiny_VISp5_175"
is_inhibitory = false

# Мембрана
threshold = 38812
rest_potential = 10087
leak_rate = 154
refractory_period = 11
spontaneous_firing_period_ticks = 956

# Адаптация и Тайминги
homeostasis_penalty = 1380
homeostasis_decay = 2
synapse_refractory_period = 15
signal_propagation_length = 29

# Рост и Морфология
steering_fov_deg = 34.4
steering_radius_um = 66.7
growth_vertical_bias = 0.95
dendrite_radius_um = 420.0
type_affinity = 0.8
sprouting_weight_distance = 0.5
sprouting_weight_power = 0.4
sprouting_weight_explore = 0.207
sprouting_weight_type = 0.2
steering_weight_inertia = 0.5
steering_weight_sensor = 0.4
steering_weight_jitter = 0.1

# Пластичность GSOP
initial_synapse_weight = 201
gsop_potentiation = 127
gsop_depression = 77
inertia_curve = [128, 119, 111, 104, 97, 90, 84, 78, 73, 68, 64, 59, 55, 52, 48, 45]
prune_threshold = 5

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 75
slot_decay_wm = 233
ltm_slot_count = 86
