[[neuron_type]]
name = "L3_aspiny_MTG_6"
threshold = -65718
rest_potential = -65730
leak_shift = 8
homeostasis_penalty = 1000
spontaneous_firing_period_ticks = 213
initial_synapse_weight = 50
gsop_potentiation = 200
gsop_depression = 2
homeostasis_decay = 11
refractory_period = 22
synapse_refractory_period = 15
signal_propagation_length = 24
is_inhibitory = true
inertia_curve = [128, 126, 124, 122, 120, 118, 116, 115,]
ahp_amplitude = 5000
adaptive_leak_min_shift = 6
adaptive_leak_gain = 0
adaptive_mode = 0
d1_affinity = 64
d2_affinity = 255

# --- Baker Sprouting Params (Not in VRAM) ---
steering_fov_deg = 147.2
steering_radius_um = 33.0
growth_vertical_bias = 0.16
dendrite_radius_um = 150.0
type_affinity = 0.2
sprouting_weight_distance = 0.7
sprouting_weight_power = 0.3
sprouting_weight_explore = 0.067
sprouting_weight_type = 0.3
steering_weight_inertia = 0.2
steering_weight_sensor = 0.6
steering_weight_jitter = 0.2
prune_threshold = 5
