[[neuron_type]]
name = "Excitatory"
threshold = 11000
rest_potential = 10000
leak_rate = 10
refractory_period = 15
synapse_refractory_period = 10

signal_propagation_length = 15
homeostasis_penalty = 5000
homeostasis_decay = 10
slot_decay_ltm = 160
slot_decay_wm = 96
steering_radius_um = 100.0 # 100 микрон - радиус поиска дендритов
gsop_potentiation = 80
gsop_depression = 20
prune_threshold = 15
ltm_slot_count = 80
is_inhibitory = false
initial_synapse_weight = 2000
inertia_curve = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
