[[neuron_type]]
name = "L5_spiny_MTG_12"
is_inhibitory = false

# Мембрана
threshold = 32499
rest_potential = 17749
leak_rate = 500
refractory_period = 16
spontaneous_firing_period_ticks = 1395

# Адаптация и Тайминги
homeostasis_penalty = 2812
homeostasis_decay = 2
synapse_refractory_period = 15
signal_propagation_length = 52

# Рост и Морфология
steering_fov_deg = 20.0
steering_radius_um = 464.4
growth_vertical_bias = 0.3
dendrite_radius_um = 1054.7
type_affinity = 0.8
sprouting_weight_distance = 0.3
sprouting_weight_power = 0.5
sprouting_weight_explore = 0.14
sprouting_weight_type = 0.1
steering_weight_inertia = 0.8
steering_weight_sensor = 0.1
steering_weight_jitter = 0.1

# Пластичность GSOP
initial_synapse_weight = 103
gsop_potentiation = 156
gsop_depression = 87
inertia_curve = [128, 111, 96, 83, 72, 63, 55, 47, 41, 36, 31, 27, 23, 20, 17, 15]
prune_threshold = 5

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 32
slot_decay_wm = 250
ltm_slot_count = 22
