[[neuron_type]]
name = "L5_spiny_MTG_9"
is_inhibitory = false

# Мембрана
threshold = 28812
rest_potential = 14274
leak_rate = 268
refractory_period = 13
spontaneous_firing_period_ticks = 3686

# Адаптация и Тайминги
homeostasis_penalty = 19517
homeostasis_decay = 2
synapse_refractory_period = 15
signal_propagation_length = 52

# Рост и Морфология
steering_fov_deg = 20.0
steering_radius_um = 247.2
growth_vertical_bias = 0.55
dendrite_radius_um = 1042.5
type_affinity = 0.8
sprouting_weight_distance = 0.3
sprouting_weight_power = 0.5
sprouting_weight_explore = 0.12
sprouting_weight_type = 0.1
steering_weight_inertia = 0.8
steering_weight_sensor = 0.1
steering_weight_jitter = 0.1

# Пластичность GSOP
initial_synapse_weight = 101
gsop_potentiation = 490
gsop_depression = 141
inertia_curve = [128, 48, 18, 6, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
prune_threshold = 5

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 32
slot_decay_wm = 250
