[[neuron_type]]
name = "L6a_aspiny_VISp6a_16"
is_inhibitory = true

# Мембрана
threshold = 27499
rest_potential = 13179
leak_rate = 114
refractory_period = 13
spontaneous_firing_period_ticks = 891

# Адаптация и Тайминги
homeostasis_penalty = 1000
homeostasis_decay = 2
synapse_refractory_period = 15
signal_propagation_length = 14

# Рост и Морфология
steering_fov_deg = 130.0
steering_radius_um = 500.0
growth_vertical_bias = 0.26
dendrite_radius_um = 103.2
type_affinity = 0.2
sprouting_weight_distance = 0.7
sprouting_weight_power = 0.3
sprouting_weight_explore = 0.12
sprouting_weight_type = 0.3
steering_weight_inertia = 0.2
steering_weight_sensor = 0.6
steering_weight_jitter = 0.2

# Пластичность GSOP
initial_synapse_weight = 429
gsop_potentiation = 199
gsop_depression = 2
inertia_curve = [128, 121, 115, 110, 104, 99, 94, 90, 85, 81, 77, 73, 70, 66, 63, 60]
prune_threshold = 107

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 128
slot_decay_wm = 128
ltm_slot_count = 64
