# config/zones/RobotBrain/blueprints.toml

[[neuron_type]]
name = "Sensory"
threshold = 35000
rest_potential = 10000
leak_rate = 1000
refractory_period = 10
synapse_refractory_period = 10
conduction_velocity = 250
homeostasis_penalty = 1000
homeostasis_decay = 20
slot_decay_ltm = 120
slot_decay_wm = 120
gsop_potentiation = 20 
gsop_depression = 10
signal_propagation_length = 255
inertia_curve = [128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 16]
growth_vertical_bias = 0.9

[[neuron_type]]
name = "Relay"
threshold = 15000
rest_potential = 10000
leak_rate = 900
refractory_period = 1
synapse_refractory_period = 1
conduction_velocity = 200
homeostasis_penalty = 125
homeostasis_decay = 40
slot_decay_ltm = 160
slot_decay_wm = 96
gsop_potentiation = 74
gsop_depression = 4
signal_propagation_length = 255
inertia_curve = [128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 8]
growth_vertical_bias = 0.7

[[neuron_type]]
name = "Inhibitory"
is_inhibitory = true
threshold = 30000
rest_potential = 10000
leak_rate = 1500
refractory_period = 10
synapse_refractory_period = 5
conduction_velocity = 100
homeostasis_penalty = 3000
homeostasis_decay = 15
slot_decay_ltm = 140
slot_decay_wm = 80
gsop_potentiation = 40
gsop_depression = 8
signal_propagation_length = 150
inertia_curve = [128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 16]
growth_vertical_bias = 0.3
