[[neuron_type]]
name = "jy170927_B_idA"
is_inhibitory = true

# Мембрана
threshold = 42000
rest_potential = 17000
leak_rate = 100
refractory_period = 19
spontaneous_firing_period_ticks = 1000

# Адаптация и Тайминги
homeostasis_penalty = 1000
homeostasis_decay = 4
synapse_refractory_period = 15
signal_propagation_length = 20

# Рост и Морфология
steering_fov_deg = 60.0
steering_radius_um = 100.0
growth_vertical_bias = 0.3
dendrite_radius_um = 200.0
type_affinity = 0.5
sprouting_weight_distance = 0.5
sprouting_weight_power = 0.4
sprouting_weight_explore = 0.12
sprouting_weight_type = 0.2
steering_weight_inertia = 0.6
steering_weight_sensor = 0.3
steering_weight_jitter = 0.1

# Пластичность GSOP
initial_synapse_weight = 375
gsop_potentiation = 74
gsop_depression = 2
inertia_curve = [128, 121, 115, 110, 104, 99, 94, 90, 85, 81, 77, 73, 70, 66, 63, 60]
prune_threshold = 93

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 128
slot_decay_wm = 128
