[[neuron_type]]
name = "L6a_spiny_VISp6a_10"
is_inhibitory = false

# Мембрана
threshold = 39656
rest_potential = 3688
leak_rate = 162
refractory_period = 13
spontaneous_firing_period_ticks = 1322

# Адаптация и Тайминги
homeostasis_penalty = 1440
homeostasis_decay = 2
synapse_refractory_period = 15
signal_propagation_length = 20

# Рост и Морфология
steering_fov_deg = 34.4
steering_radius_um = 66.7
growth_vertical_bias = 0.95
dendrite_radius_um = 250.0
type_affinity = 0.8
sprouting_weight_distance = 0.5
sprouting_weight_power = 0.4
sprouting_weight_explore = 0.1
sprouting_weight_type = 0.2
steering_weight_inertia = 0.5
steering_weight_sensor = 0.4
steering_weight_jitter = 0.1

# Пластичность GSOP
initial_synapse_weight = 251
gsop_potentiation = 128
gsop_depression = 77
inertia_curve = [128, 119, 110, 103, 95, 89, 83, 77, 71, 66, 62, 57, 53, 50, 46, 43]
prune_threshold = 5

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 96
slot_decay_wm = 190
ltm_slot_count = 103
