[[neuron_type]]
name = "L3_aspiny_MTG_45"
is_inhibitory = true

# Мембрана
threshold = 20999
rest_potential = 12053
leak_rate = 70
refractory_period = 22
spontaneous_firing_period_ticks = 652

# Адаптация и Тайминги
homeostasis_penalty = 1440
homeostasis_decay = 3
synapse_refractory_period = 15
signal_propagation_length = 24

# Рост и Морфология
steering_fov_deg = 147.2
steering_radius_um = 33.0
growth_vertical_bias = 0.16
dendrite_radius_um = 150.0
type_affinity = 0.2
sprouting_weight_distance = 0.7
sprouting_weight_power = 0.3
sprouting_weight_explore = 0.127
sprouting_weight_type = 0.3
steering_weight_inertia = 0.2
steering_weight_sensor = 0.6
steering_weight_jitter = 0.2

# Пластичность GSOP
initial_synapse_weight = 268
gsop_potentiation = 207
gsop_depression = 2
inertia_curve = [128, 119, 110, 103, 95, 89, 83, 77, 71, 66, 62, 57, 53, 50, 46, 43]
prune_threshold = 67

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 128
slot_decay_wm = 128
ltm_slot_count = 64
