[[neuron_type]]
name = "L3_spiny_MTG_58"
is_inhibitory = false

# Мембрана
threshold = 29687
rest_potential = 18544
leak_rate = 315
refractory_period = 10
spontaneous_firing_period_ticks = 1307

# Адаптация и Тайминги
homeostasis_penalty = 1000
homeostasis_decay = 2
synapse_refractory_period = 15
signal_propagation_length = 46

# Рост и Морфология
steering_fov_deg = 20.0
steering_radius_um = 359.7
growth_vertical_bias = 0.3
dendrite_radius_um = 920.3
type_affinity = 0.8
sprouting_weight_distance = 0.3
sprouting_weight_power = 0.5
sprouting_weight_explore = 0.163
sprouting_weight_type = 0.1
steering_weight_inertia = 0.8
steering_weight_sensor = 0.1
steering_weight_jitter = 0.1

# Пластичность GSOP
initial_synapse_weight = 78
gsop_potentiation = 116
gsop_depression = 73
inertia_curve = [128, 121, 115, 110, 104, 99, 94, 90, 85, 81, 77, 73, 70, 66, 63, 60]
prune_threshold = 5

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 32
slot_decay_wm = 250
ltm_slot_count = 35
