zone_id = "HiddenCortex"

[world_offset]
x = 0
y = 0
z = 0

[dimensions]
w = 64
d = 64
h = 63

[settings]
night_interval_ticks = 400_000
save_checkpoints_interval_ticks = 400_000

[neighbors]
x = "Self"
y = "Self"