[[neuron_type]]
name = "L5_aspiny_VISp5_172"
is_inhibitory = true

# Мембрана
threshold = 17875
rest_potential = 8813
leak_rate = 125
refractory_period = 21
spontaneous_firing_period_ticks = 321

# Адаптация и Тайминги
homeostasis_penalty = 1345
homeostasis_decay = 7
synapse_refractory_period = 15
signal_propagation_length = 22

# Рост и Морфология
steering_fov_deg = 147.2
steering_radius_um = 33.0
growth_vertical_bias = 0.22
dendrite_radius_um = 150.0
type_affinity = 0.2
sprouting_weight_distance = 0.7
sprouting_weight_power = 0.3
sprouting_weight_explore = 0.3
sprouting_weight_type = 0.3
steering_weight_inertia = 0.2
steering_weight_sensor = 0.6
steering_weight_jitter = 0.2

# Пластичность GSOP
initial_synapse_weight = 271
gsop_potentiation = 206
gsop_depression = 2
inertia_curve = [128, 119, 111, 104, 97, 91, 85, 79, 74, 69, 65, 61, 57, 53, 49, 46]
prune_threshold = 67

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 128
slot_decay_wm = 128
