[[neuron_type]]
name = "L5_aspiny_VISp5_81"
is_inhibitory = true

# Мембрана
threshold = 25125
rest_potential = 10719
leak_rate = 216
refractory_period = 17
spontaneous_firing_period_ticks = 440

# Адаптация и Тайминги
homeostasis_penalty = 1000
homeostasis_decay = 5
synapse_refractory_period = 15
signal_propagation_length = 18

# Рост и Морфология
steering_fov_deg = 147.2
steering_radius_um = 33.0
growth_vertical_bias = 0.22
dendrite_radius_um = 150.0
type_affinity = 0.2
sprouting_weight_distance = 0.7
sprouting_weight_power = 0.3
sprouting_weight_explore = 0.3
sprouting_weight_type = 0.3
steering_weight_inertia = 0.2
steering_weight_sensor = 0.6
steering_weight_jitter = 0.2

# Пластичность GSOP
initial_synapse_weight = 1500
gsop_potentiation = 20
gsop_depression = 24
inertia_curve = [128, 123, 117, 112, 106, 100, 94, 87, 81, 74, 66, 58, 50, 40, 28, 7]
prune_threshold = 100

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 128
slot_decay_wm = 128
ltm_slot_count = 64
