[[neuron_type]]
name = "L4_spiny_VISp4_50"
is_inhibitory = false

# Мембрана
threshold = 36499
rest_potential = 4753
leak_rate = 159
refractory_period = 14
spontaneous_firing_period_ticks = 1032

# Адаптация и Тайминги
homeostasis_penalty = 1213
homeostasis_decay = 2
synapse_refractory_period = 15
signal_propagation_length = 20

# Рост и Морфология
steering_fov_deg = 34.4
steering_radius_um = 66.7
growth_vertical_bias = 0.95
dendrite_radius_um = 250.0
type_affinity = 0.8
sprouting_weight_distance = 0.5
sprouting_weight_power = 0.4
sprouting_weight_explore = 0.1
sprouting_weight_type = 0.2
steering_weight_inertia = 0.5
steering_weight_sensor = 0.4
steering_weight_jitter = 0.1

# Пластичность GSOP
initial_synapse_weight = 222
gsop_potentiation = 124
gsop_depression = 76
inertia_curve = [128, 120, 113, 106, 100, 94, 88, 83, 78, 74, 69, 65, 61, 58, 54, 51]
prune_threshold = 5

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 96
slot_decay_wm = 190
ltm_slot_count = 103
