[[layer]]
name = "L4"
height_pct = 0.60
population_pct = 0.60
[layer.composition]
"Vertical_Excitatory" = 0.80
"Horizontal_Inhibitory" = 0.20

[[layer]]
name = "L2/3"
height_pct = 0.40
population_pct = 0.40
[layer.composition]
"Vertical_Excitatory" = 0.85
"Horizontal_Inhibitory" = 0.15
