[world]
width_um = 3500
depth_um = 3500
height_um = 10250

[simulation]
tick_duration_us = 100
total_ticks = 10000
master_seed = "GENESIS"
global_density = 0.04
voxel_size_um = 25
signal_speed_um_tick = 50
sync_batch_ticks = 1000
axon_growth_max_steps = 1500
