[[neuron_type]]
name = "L23_spiny_VISp23_27"
is_inhibitory = false

# Мембрана
threshold = 39406
rest_potential = 13363
leak_rate = 196
refractory_period = 10
spontaneous_firing_period_ticks = 824

# Адаптация и Тайминги
homeostasis_penalty = 10000
homeostasis_decay = 3
synapse_refractory_period = 15
signal_propagation_length = 20

# Рост и Морфология
steering_fov_deg = 34.4
steering_radius_um = 66.7
growth_vertical_bias = 0.54
dendrite_radius_um = 300.0
type_affinity = 0.8
sprouting_weight_distance = 0.5
sprouting_weight_power = 0.4
sprouting_weight_explore = 0.1
sprouting_weight_type = 0.2
steering_weight_inertia = 0.5
steering_weight_sensor = 0.4
steering_weight_jitter = 0.1

# Пластичность GSOP
initial_synapse_weight = 182
gsop_potentiation = 300
gsop_depression = 120
inertia_curve = [128, 77, 47, 28, 17, 10, 6, 3, 2, 1, 1, 1, 1, 1, 1, 1]
prune_threshold = 5

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 90
slot_decay_wm = 203
