[simulation]
config = "config/simulation.toml"

[[zone]]
name = "SensoryCortex"
blueprints = "config/brains/RobotBrain/blueprints.toml"
anatomy = "config/brains/RobotBrain/SensoryCortex/anatomy.toml"
io = "config/brains/RobotBrain/SensoryCortex/io.toml"
baked_dir = "baked/SensoryCortex"

[[zone]]
name = "HiddenCortex"
blueprints = "config/brains/RobotBrain/blueprints.toml"
anatomy = "config/brains/RobotBrain/HiddenCortex/anatomy.toml"
io = "config/brains/RobotBrain/HiddenCortex/io.toml"
baked_dir = "baked/HiddenCortex"

[[zone]]
name = "MotorCortex"
blueprints = "config/brains/RobotBrain/blueprints.toml"
anatomy = "config/brains/RobotBrain/MotorCortex/anatomy.toml"
io = "config/brains/RobotBrain/MotorCortex/io.toml"
baked_dir = "baked/MotorCortex"

[[connection]]
from = "SensoryCortex"
to = "HiddenCortex"
target_type = "All"
width = 2
height = 2
growth_steps = 100 # Allow lots of growth steps to bridge the gap

[[connection]]
from = "HiddenCortex"
to = "MotorCortex"
target_type = "All"
growth_steps = 0
