[simulation]
config = "config/simulation.toml"

[[zone]]
name = "SensoryCortex"
blueprints = "config/brains/RobotBrain/blueprints.toml"
anatomy = "config/brains/RobotBrain/SensoryCortex/anatomy.toml"
io = "config/brains/RobotBrain/SensoryCortex/io.toml"
baked_dir = "baked/SensoryCortex"

[[zone]]
name = "HiddenCortex"
blueprints = "config/brains/RobotBrain/blueprints.toml"
anatomy = "config/brains/RobotBrain/HiddenCortex/anatomy.toml"
io = "config/brains/RobotBrain/HiddenCortex/io.toml"
baked_dir = "baked/HiddenCortex"

[[zone]]
name = "MotorCortex"
blueprints = "config/brains/RobotBrain/blueprints.toml"
anatomy = "config/brains/RobotBrain/MotorCortex/anatomy.toml"
io = "config/brains/RobotBrain/MotorCortex/io.toml"
baked_dir = "baked/MotorCortex"

# Сенсорно-Ассоциативный тракт (расширяем до 1024 волокон)
[[connection]]
from = "SensoryCortex"
to = "HiddenCortex"
target_type = "All"
width = 32
height = 32
growth_steps = 100

# Ассоциативно-Моторный тракт (включаем UV-проекцию, 1024 волокна)
[[connection]]
from = "HiddenCortex"
to = "MotorCortex"
target_type = "All"
width = 32
height = 32
growth_steps = 500
