[[neuron_type]]
name = "4-3-19_Enuc_2-4_Cell_4"
is_inhibitory = false

# Membrane
threshold = 37000
rest_potential = 17000
leak_shift = 4
ahp_amplitude = 0
adaptive_leak_min_shift = 0
refractory_period = 14
spontaneous_firing_period_ticks = 5000

# Adaptation and Timings
homeostasis_penalty = 10000
homeostasis_decay = 2
synapse_refractory_period = 15
signal_propagation_length = 28

# Growth and Morphology
steering_fov_deg = 60.0
steering_radius_um = 100.0
growth_vertical_bias = 0.7
dendrite_radius_um = 200.0
type_affinity = 0.5
sprouting_weight_distance = 0.5
sprouting_weight_power = 0.4
sprouting_weight_explore = 0.17
sprouting_weight_type = 0.2
steering_weight_inertia = 0.6
steering_weight_sensor = 0.3
steering_weight_jitter = 0.1

# Synaptic Plasticity (GSOP)
initial_synapse_weight = 1000
gsop_potentiation = 18
gsop_depression = 21
inertia_curve = [ 128, 108, 88, 66, 41, 22, 8, 0,]
prune_threshold = 100

# --- Dynamic Slot Decay (Derived) ---
slot_decay_ltm = 103
slot_decay_wm = 178
ltm_slot_count = 108

