# L1: Молекулярный слой
[[layer]]
name = "L1"
height_pct = 0.10
density = 0.01
composition = { "L1_aspiny_MTG_3" = 1.0 }

# L2/3: Премоторная интеграция
[[layer]]
name = "L23"
height_pct = 0.30
density = 0.04
composition = { "L2_spiny_MFG_1" = 0.8, "L3_aspiny_MFG_1" = 0.2 }

# L5: Главный моторный тракт (Клетки Беца). Занимает почти половину коры.
[[layer]]
name = "L5"
height_pct = 0.40
density = 0.02
composition = { "L5_spiny_MFG_1" = 0.5, "L5_spiny_MFG_3" = 0.3, "L5_aspiny_MFG_1" = 0.2 }

# L6: Обратная связь
[[layer]]
name = "L6"
height_pct = 0.20
density = 0.03
composition = { "L6_spiny_MFG_1" = 0.8, "L6_aspiny_MTG_2" = 0.2 }
