[[neuron_type]]
name = "L5_spiny_RSPd5_2"
threshold = -50093
rest_potential = -73196
leak_shift = 7
homeostasis_penalty = 1000
spontaneous_firing_period_ticks = 593
initial_synapse_weight = 462
gsop_potentiation = 103
gsop_depression = 67
homeostasis_decay = 4
refractory_period = 21
synapse_refractory_period = 15
signal_propagation_length = 20
is_inhibitory = false
inertia_curve = [128, 125, 123, 121, 119, 117, 115, 113,]
ahp_amplitude = 5000
adaptive_leak_min_shift = 5
adaptive_leak_gain = 0
adaptive_mode = 0
d1_affinity = 192
d2_affinity = 128

# --- Baker Sprouting Params (Not in VRAM) ---
steering_fov_deg = 34.4
steering_radius_um = 66.7
growth_vertical_bias = 0.95
dendrite_radius_um = 420.0
type_affinity = 0.8
sprouting_weight_distance = 0.5
sprouting_weight_power = 0.4
sprouting_weight_explore = 0.1
sprouting_weight_type = 0.2
steering_weight_inertia = 0.5
steering_weight_sensor = 0.4
steering_weight_jitter = 0.1
prune_threshold = 5
