connection = []
[[zone]]
name = "SensoryCortex"
blueprints = "/home/alex/Workflow/Genesis/Genesis-Models/CartPole-example/SensoryCortex/blueprints.toml"
anatomy = "/home/alex/Workflow/Genesis/Genesis-Models/CartPole-example/SensoryCortex/anatomy.toml"
shard = "/home/alex/Workflow/Genesis/Genesis-Models/CartPole-example/SensoryCortex/shard.toml"
io = "/home/alex/Workflow/Genesis/Genesis-Models/CartPole-example/SensoryCortex/io.toml"
baked_dir = "/home/alex/Workflow/Genesis/Genesis-Models/CartPole-example/baked/SensoryCortex"

[simulation]
config = "/home/alex/Workflow/Genesis/Genesis-Models/CartPole-example/simulation.toml"
