[[neuron_type]]
name = "L5_spiny_VISl5_8"
is_inhibitory = false

# Мембрана
threshold = 37968
rest_potential = 12345
leak_rate = 169
refractory_period = 17
spontaneous_firing_period_ticks = 653

# Адаптация и Тайминги
homeostasis_penalty = 1000
homeostasis_decay = 3
synapse_refractory_period = 15
signal_propagation_length = 20

# Рост и Морфология
steering_fov_deg = 34.4
steering_radius_um = 66.7
growth_vertical_bias = 0.95
dendrite_radius_um = 420.0
type_affinity = 0.8
sprouting_weight_distance = 0.5
sprouting_weight_power = 0.4
sprouting_weight_explore = 0.1
sprouting_weight_type = 0.2
steering_weight_inertia = 0.5
steering_weight_sensor = 0.4
steering_weight_jitter = 0.1

# Пластичность GSOP
initial_synapse_weight = 179
gsop_potentiation = 109
gsop_depression = 70
inertia_curve = [128, 121, 115, 110, 104, 99, 94, 90, 85, 81, 77, 73, 70, 66, 63, 60]
prune_threshold = 5

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 75
slot_decay_wm = 233
ltm_slot_count = 86
