[[neuron_type]]
name = "L1_sparsely spiny_MTG_1"
is_inhibitory = true

# Membrane
threshold = 42134
rest_potential = 22134
leak_rate = 138
refractory_period = 19
spontaneous_firing_period_ticks = 200

# Adaptation and Timings
homeostasis_penalty = 1000
homeostasis_decay = 12
synapse_refractory_period = 15
signal_propagation_length = 20

# Growth and Morphology
steering_fov_deg = 55.0
steering_radius_um = 500.0
growth_vertical_bias = 0.11
dendrite_radius_um = 69.1
type_affinity = 0.5
sprouting_weight_distance = 0.7
sprouting_weight_power = 0.3
sprouting_weight_explore = 0.087
sprouting_weight_type = 0.3
steering_weight_inertia = 0.2
steering_weight_sensor = 0.6
steering_weight_jitter = 0.2

# Synaptic Plasticity (GSOP)
initial_synapse_weight = 1500
gsop_potentiation = 20
gsop_depression = 24
inertia_curve = [128, 121, 114, 107, 100, 92, 85, 77, 70, 62, 54, 46, 37, 28, 19, 7]
prune_threshold = 100

# --- Dynamic Slot Decay (Derived) ---
slot_decay_ltm = 128
slot_decay_wm = 128
ltm_slot_count = 64

