[[neuron_type]]
name = "L23_aspiny_VISp23_177"
is_inhibitory = true

# Мембрана
threshold = 21156
rest_potential = 15878
leak_rate = 256
refractory_period = 20
spontaneous_firing_period_ticks = 663

# Адаптация и Тайминги
homeostasis_penalty = 4153
homeostasis_decay = 3
synapse_refractory_period = 15
signal_propagation_length = 21

# Рост и Морфология
steering_fov_deg = 147.2
steering_radius_um = 33.0
growth_vertical_bias = 0.14
dendrite_radius_um = 150.0
type_affinity = 0.2
sprouting_weight_distance = 0.7
sprouting_weight_power = 0.3
sprouting_weight_explore = 0.123
sprouting_weight_type = 0.3
steering_weight_inertia = 0.2
steering_weight_sensor = 0.6
steering_weight_jitter = 0.2

# Пластичность GSOP
initial_synapse_weight = 158
gsop_potentiation = 220
gsop_depression = 2
inertia_curve = [128, 103, 84, 68, 55, 45, 36, 29, 24, 19, 16, 13, 10, 8, 6, 5]
prune_threshold = 39

# --- Динамический Slot Decay (Derived) ---
slot_decay_ltm = 128
slot_decay_wm = 128
