# config/zones/RobotBrain/SensoryCortex/anatomy.toml

[[layer]]
name = "L2_3" # Superficial feedback
height_pct = 0.3
population_pct = 0.3
[layer.composition]
"Relay" = 0.8
"Inhibitory" = 0.2

[[layer]]
name = "L4" # Primary Input
height_pct = 0.4
population_pct = 0.4
[layer.composition]
"Sensory" = 0.8
"Inhibitory" = 0.2

[[layer]]
name = "L5_6" # Output/Projection
height_pct = 0.3
population_pct = 0.3
[layer.composition]
"Relay" = 0.8
"Inhibitory" = 0.2
